# -*- mode: ruby -*-
# vim: set ft=ruby :


MACHINES = {
  :otusRaidHomeWork => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 250, # Megabytes
			            :port => 2
		},
         :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 250,
                        :port => 3
        },
         :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 250, # Megabytes
                        :port => 4
        },
         :sata5 => {
                        :dfile => './sata5.vdi',
                        :size => 250, # Megabytes
                        :port => 5
        },
        :sata6 => {
                        :dfile => './sata6.vdi',
                        :size => 250, # Megabytes
                        :port => 6
                }


	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
     #box.vm.synced_folder "./files/","/home/vagrant/test"
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
		  
	#mdadm --zero-superblock --force /dev/sd{b,c,d,e,f,g}
	
    sudo mdadm -C /dev/md0 -N myRaidOne  -e default -l 1 -n 2 /dev/sd{b,c}
    sudo mdadm -C /dev/md1 -N myRaidTwo  -e default -l 1 -n 2 /dev/sd{d,e}
    sudo mdadm -C /dev/md2 -N myRaidThree  -e default -l 1 -n 2 /dev/sd{f,g}
	sudo mdadm -C /dev/md3 -N myRaidFour  -e default -l 0 -n 3 /dev/md{0,1,2}
	
	mkdir /etc/mdadm
	echo "DEVICE partitions" > /etc/mdadm/mdadm.conf
	mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
	
	
	parted -s /dev/md3 mklabel gpt
	parted /dev/md3 mkpart primary ext4 0% 20%
	parted /dev/md3 mkpart primary ext4 20% 40%
	parted /dev/md3 mkpart primary ext4 40% 60%
	parted /dev/md3 mkpart primary ext4 60% 80%
	parted /dev/md3 mkpart primary ext4 80% 100%
		
	for i in $(seq 1 5); do sudo mkfs.ext4 /dev/md3p$i; done	
	mkdir -p /raid/part{1,2,3,4,5} 
	for i in $(seq 1 5); do mount /dev/md3p$i /raid/part$i; done
	
  	  SHELL

      end
  end
end

